<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.3.5/themes/gray/easyui.css">
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.3.5/themes/icon.css">
    <script type="text/javascript" src="/jquery-easyui-1.3.5/jquery.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.3.5/jquery.easyui.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.3.5/locale/easyui-lang-zh_CN.js"></script>

</head>
<body>
<!--<div align="right"><a title="点击" class="easyui-tooltip"><img src="/images/help.png"></a></div>
-->
<div id="tb" align="right">
    <form action='/kb/search' method="post" id="fm">
        <select class="easyui-combobox" name="type">
            <option value="0">--类型--</option>
            <?php
            $typemessage = $this->typemessage;
            for($j=0;$j<count($typemessage);$j++)
            {
                echo "<option value='".$typemessage[$j]['type_id']."'>".$typemessage[$j]['type_name']."</option>";
            }
            ?>
        </select>
        <input name="point" type="search" value="关键字">
        <input type="submit" value="搜索">
    </form>
</div>
<table id="tt"></table>
</body>
</html>
<script>
    $(function () {
        $('#tt').datagrid({
            fit: true,
            fitColumns: true,
            rownumbers: true,
            method: 'GET',
            toolbar: '#tb',
            url: '/kb/kbmessage',
            pagination: true,
            singleSelect: true,
            pageSize : 5,
            pageList : [5,10,15],
            columns:[[
                {field:'type_name',title:'类型',width:100},
                {field:'task_describe',title:'任务描述',width:100},
                {field:'process',title:'任务过程',width:100},
                {field:'view',title:'查看',width:35,align:"center",
                    formatter: function(value,row,index){
                        var v = '<input type="button" href="#" value="查看" onclick="view('+row.KB_id+')">';
                        return v;
                    }
                }
            ]]
        });
    });
    function view(id)
    {
        window.location.href="/kb/view?id="+id+"&&f=1";
    }

</script>
