<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.4.5/themes/gray/easyui.css">
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.4.5/themes/icon.css">
    <script type="text/javascript" src="/jquery-easyui-1.4.5/jquery.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.4.5/jquery.easyui.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.4.5/locale/easyui-lang-zh_CN.js"></script>

</head>
<?php
$message = $this->message;
?>

<div>
    <a href="/kb/kb" class="easyui-linkbutton" data-options="iconCls:'icon-undo'">返回</a>
</div>


    <?php
    if(empty($message))
    {

        echo "<div align='center'><h2>无符合条件的数据，请返回</h2></div>";
    }else{
        for($i=0;$i<count($message);$i++)
        {
            echo"
            <div  class='easyui-panel'>
            <h3>任务描述</h3><br />".$message[$i]['task_describe']."<br />
            <h3>处理描述</h3><br />".$message[$i]['process']."<br /></div>";
        }
    }


    ?>



</body>
</html>
