<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.3.5/themes/gray/easyui.css">
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.3.5/themes/icon.css">
    <script type="text/javascript" src="/jquery-easyui-1.3.5/jquery.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.3.5/jquery.easyui.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.3.5/locale/easyui-lang-zh_CN.js"></script>

</head>
<body>
<table id="tt"></table>
</body>
</html>
<script>
    $(function(){
        $('#tt').datagrid({
            fit: true,
            fitColumns: true,
            rownumbers: true,
            method: 'GET',
            toolbar: '#tb',
            url: '/task/finishedmessage',
            pagination: true,
            singleSelect: true,
            pageSize : 10,
            pageList : [5,10,15],
            columns:[[
                {field:'event',title:'事件来源',width:20},
                {field:'task_describe',title:'任务描述',width:90},
                {field:'process',title:'过程描述',width:90},
                {field:'start_time',title:'开始时间',width:40},
                {field:'finish_time',title:'完成时间',width:40},
                {field:'type',title:'类别',width:20},
                {field:'log',title:'任务记录表',width:20,
                    formatter: function(value,row,index){
                        var s="<input type='button' onclick='view("+row.task_id+")' value='查看'>";
                        return s;
                        }
                }
            ]]
        });
    });
    function view(id)
    {
        window.open("/task/tasklog?task_id="+id+"&&f=1");
    }
</script>