<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.4.5/themes/gray/easyui.css">
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.4.5/themes/icon.css">
    <script type="text/javascript" src="/jquery-easyui-1.4.5/jquery.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.4.5/jquery.easyui.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.4.5/locale/easyui-lang-zh_CN.js"></script>
</head>

<body>
<?php
$task_id = $this->task_id;
$message = $this->message;
?>
<div>
    <a href="/task/unfinished" class="easyui-linkbutton" data-options="iconCls:'icon-undo'">返回</a>
</div>

<div class="easyui-panel" title="事件跟踪">
    <?php
    for($i=0;$i<count($message);$i++)
    {
        if($message[$i]['state']==0)
        {
            echo "<p>未完成</p>";
        }elseif($message[$i]['state']==1){
            echo "<p>挂起</p>";
        }
       echo $message[$i]['Fdescribe']."<br>";
    }
    ?>
    <br>
    <div>
        状态
        <select id="state">
            <option value="0">未完成</option>
            <option value="1">挂起</option>
        </select>
        <textarea id="Fdescribe" style="width:100%;height:40%"><?php echo date('Y-'.'m-'.'j'); ?>  </textarea>
    </div>
</div>
<div align="center" style="margin-top: 5px">
    <a class="easyui-linkbutton" iconCls="icon-ok" onClick="submit()">提交</a>
</div>



</body>
</html>

<script type="text/javascript">
    function submit() {
        //alert(1);
        var state = $('#state').val();
        var Fdescribe = document.getElementById("Fdescribe").value;

        $.ajax({ //调用jquery的ajax方法
            type: "POST", //设置ajax方法提交数据的形式
            data: {
                'state' : state,
                'Fdescribe': Fdescribe,
                'task_id': <?php echo $task_id; ?>
            },
            url: "/task/submitfollowing",
            success: function (msg) {
                /*alert(msg);*/
                if(msg)
                {
                    window.location.href="/task/unfinished";
                }else{
                    alert("提交失败");
                }
            }
        })
    }
</script>