<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.4.5/themes/gray/easyui.css">
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.4.5/themes/icon.css">
    <script type="text/javascript" src="/jquery-easyui-1.4.5/jquery.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.4.5/jquery.easyui.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.4.5/locale/easyui-lang-zh_CN.js"></script>

</head>

<body>
<div id="toolbar">
    <a href="/task/register" class="easyui-linkbutton" data-options="iconCls:'icon-undo'">返回</a>
</div>
<table id="dg" class="easyui-datagrid"
       fit="true"
       toolbar="#toolbar" pagination="true" fitColumns="true" singleSelect="true">
    <thead>
    <tr>
        <th field="state" width="60">状态</th>
        <th field="describe" width="200">事件跟踪</th>
    </tr>
    </thead>
    <tbody>
    <?php
    $message = $this->message;
    for ($i=0;$i<count($message);$i++)
    {
          echo"<tr><td>";
           if($message[$i]['state']==0)
           {
               echo "未完成";
           }elseif($message[$i]['state']==1){
               echo "挂起";
           }else{
               echo "完成";
           }
          echo"</td><td>".$message[$i]['Fdescribe']."
               </tr>";
    }
    ?>
    </tbody>
</table>

</body>
</html>