<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.3.5/themes/gray/easyui.css">
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.3.5/themes/icon.css">
    <script type="text/javascript" src="/jquery-easyui-1.3.5/jquery.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.3.5/jquery.easyui.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.3.5/locale/easyui-lang-zh_CN.js"></script>

</head>
<body>
<!--<div align="right"><a title="点击" class="easyui-tooltip"><img src="/images/help.png"></a></div>
-->
<div id="tb" align="right">
    <form action='/task/register' method="post" id="fm">
        <select name="state">
            <option>状态</option>
            <option value="1">未完成</option>
            <option value="2">已完成</option>
            <option value="0">全部</option>
        </select>
        <input type="submit" value="搜索">
    </form>
</div>
<table id="tt"></table>
</body>
</html>
<script>
    $(function(){
        $('#tt').datagrid({
            fit: true,
            fitColumns: true,
            rownumbers: true,
            method: 'GET',
            toolbar: '#tb',
            <?php
            $state=$this->state;
            if($state)
            {
                echo "url: '/task/registermessage?state=".$state."',";
            }else{
                echo "url: '/task/registermessage',";
            }
            ?>
            pagination: true,
            singleSelect: true,
            pageSize : 10,
            pageList : [5,10,15],
            columns:[[
                {field:'task_id',title:'事件编号',width:40},
                {field:'event',title:'事件类别',width:40},
                {field:'Auser',title:'添加人员',width:40},
                {field:'Huser',title:'分配人员',width:40},
                {field:'start_time',title:'处置时间',width:90},
                {field:'Fdescribe',title:'事件跟踪',width:160,
                    formatter: function(value,row,index){
                        var s = '<input type="button" href="#" value="查看详细内容" onclick="follow('+row.task_id+')">';
                        if(value)
                        {
                            return value+"<br />"+s;
                        }else{
                            return "";
                        }

                    }},
                {field:'finish_time',title:'完成时间',width:90},
                {field:'submit',title:'提交故障报告',width:60,
                    formatter: function(value,row,index){
                        if (value==0){
                            return "未提交";
                        }
                        if (value==1){
                            var s = '<input type="button" href="#" value="已提交" onclick="view('+row.task_id+',0)">';
                            return s;
                        }
                        if (value==2){
                            var v = '<input type="button" href="#" value="可查看" onclick="view('+row.task_id+',1)">';
                            return v;
                        }
                    }
                },
                {field:'submitKB',title:'提交知识库',width:55,
                    formatter: function(value,row,index){
                        if(row.submit==2)
                        {
                            if (value==0){
                                var s = '<input type="button" href="#" value="提交知识" onclick="submit('+row.task_id+',0)">';
                                return s;
                            }
                            if (value==1){
                                var v = '<input type="button" href="#" value="撤回知识" onclick="submit('+row.task_id+',1)">';
                                return v;
                            }
                        }
                    }
                },
                {field:'KB_id',title:'知识编号',width:40},
                {field:'type',title:'知识类别',width:50},
                {field:'access',title:'人员反馈',width:45,
                    formatter: function(value,row,index){
                        if (value==0){
                            return "";
                        }
                        if (value==1){
                            return "已接受";
                        }
                        if (value==2){
                            return "已拒绝";
                        }
                    }
                },
                {field:'revoke',title:'撤回任务',width:35,
                    formatter: function(value,row,index){
                        var s = '<input type="button" href="#" value="撤回" onclick="revoke('+row.task_id+')">';
                        return s;
                    }
                }
            ]]
        });
    });

    function submit(id,flag)
    {
        $.ajax({ //调用jquery的ajax方法
            type: "POST", //设置ajax方法提交数据的形式
            data: {
                'id': id,
                'flag' : flag
            },
            url: "/task/submitkb",
            success: function () {
                window.location.reload();
            }
        })
    }
    function revoke(id)
    {
        $.messager.confirm('系统提示', '确定要撤回任务吗？撤回后将无法恢复。', function(r)//r是获取确定或取消
        {
            if (r) {
                $.ajax({ //调用jquery的ajax方法
                    type: "POST", //设置ajax方法提交数据的形式
                    data: {
                        'id': id
                    },
                    url: "/task/deletetask",
                    success: function () {
                        window.location.reload();
                    }
                })
            }
        });
    }

    function view(id,f)
    {
        window.open("/task/tasklog?task_id="+id+"&&f="+f);
    }

    function follow(id)
    {
        window.location.href="/task/followview?task_id="+id;
    }
</script>