<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.4.5/themes/gray/easyui.css">
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.4.5/themes/icon.css">
    <script type="text/javascript" src="/jquery-easyui-1.4.5/jquery.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.4.5/jquery.easyui.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.4.5/locale/easyui-lang-zh_CN.js"></script>

</head>
<?php
$task_id = $this->task_id;
?>

<div>
    <a href="/task/unfinished" class="easyui-linkbutton" data-options="iconCls:'icon-undo'">返回</a>
</div>

<div class="easyui-panel" >

    <div>
        <label>协同处理人员</label><input id="partner" type="text" value="无">
    </div>
    <div style="float:left;width: 33%">
        <div  class="easyui-panel" title="过程记录">
            <textarea id="process" style="width:100%;height:70%"></textarea>
        </div>
    </div>
    <div style="float:left;width: 34%">
    <div  class="easyui-panel" title="结果">
        <textarea id="result" style="width:100%;height:70%"></textarea>
    </div>
    </div>
    <div style="float:left;width: 33%">
    <div  class="easyui-panel" title="后续问题">
        <textarea id="follow_up" style="width:100%;height:70%"></textarea>
    </div>
    </div>

</div>
<div align="center" style="margin-top: 5px">
    <a class="easyui-linkbutton" iconCls="icon-ok" onClick="submit()">提交</a>
</div>


</body>
</html>

<script type="text/javascript">
    function submit() {
        //alert(1);
        var partner = $('#partner').val();
        var process = document.getElementById("process").value;
        var result = document.getElementById("result").value;
        var follow_up = document.getElementById("follow_up").value;
        $.ajax({ //调用jquery的ajax方法
            type: "POST", //设置ajax方法提交数据的形式
            data: {
                'process': process,
                'result': result,
                'follow_up': follow_up,
                'task_id': <?php echo $task_id; ?>,
                'partner': partner
            },
            url: "/task/submittask",
            success: function (msg) {
                /*alert(msg);*/
                if(msg)
                {
                    window.location.href="/task/finished";
                }else{
                    alert("提交失败");
                }
            }
        })
    }
</script>