<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.3.5/themes/gray/easyui.css">
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.3.5/themes/icon.css">
    <script type="text/javascript" src="/jquery-easyui-1.3.5/jquery.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.3.5/jquery.easyui.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.3.5/locale/easyui-lang-zh_CN.js"></script>

</head>
<body>
<!--<div align="right"><a title="点击" class="easyui-tooltip"><img src="/images/help.png"></a></div>
-->
<div id="toolbar" align="right">
    <form action='/task/searchregister' method="post" id="fm">
        <select name="state">
            <option>状态</option>
            <option value="1">未完成</option>
            <option value="2">已完成</option>
            <option value="0">全部</option>
        </select>
        <input type="submit" value="搜索">
    </form>
</div>
<table id="tt"></table>
</body>
</html>
<script>
    $(function(){
        $('#tt').datagrid({
            fit: true,
            fitColumns: true,
            rownumbers: true,
            method: 'GET',
            toolbar: '#tb',
            url: '/task/registermessage',
            pagination: true,
            singleSelect: true,
            pageSize : 10,
            pageList : [5,10,15],
            columns:[[
                {field:'task_id',title:'事件编号',width:50},
                {field:'event',title:'事件类别',width:50},
                {field:'Auser',title:'添加人员',width:50},
                {field:'Huser',title:'分配人员',width:50},
                {field:'start_time',title:'处置时间',width:100},
                {field:'Fdescribe',title:'事件跟踪',width:100},
                {field:'finish_time',title:'完成时间',width:100},
                {field:'submit',title:'提交故障报告',width:100},
                {field:'submitKB',title:'提交知识库',width:100},
                {field:'KB_id',title:'知识编号',width:100},
                {field:'type',title:'知识类别',width:100},
                {field:'access',title:'人员反馈',width:100},
                {field:'process',title:'撤回任务',width:100}
            ]]
        });
    });

    function submit(id,flag)
    {
        $.ajax({ //调用jquery的ajax方法
            type: "POST", //设置ajax方法提交数据的形式
            data: {
                'id': id,
                'flag' : flag
            },
            url: "/task/submitkb",
            success: function () {
                window.location.reload();
            }
        })
    }
    function revoke(id)
    {
        $.messager.confirm('系统提示', '确定要撤回任务吗？撤回后将无法恢复。', function(r)//r是获取确定或取消
        {
            if (r) {
                $.ajax({ //调用jquery的ajax方法
                    type: "POST", //设置ajax方法提交数据的形式
                    data: {
                        'id': id
                    },
                    url: "/task/deletetask",
                    success: function () {
                        window.location.reload();
                    }
                })
            }
        });
    }
</script>