<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.3.5/themes/gray/easyui.css">
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.3.5/themes/icon.css">
    <script type="text/javascript" src="/jquery-easyui-1.3.5/jquery.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.3.5/jquery.easyui.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.3.5/locale/easyui-lang-zh_CN.js"></script>

</head>
<body>
<div id="tb">
    <a href="#" class="easyui-linkbutton" onclick="insert()" data-options="iconCls:'icon-add',plain:true"/>添加</a>
</div>
<table id="tt"></table>
</body>
</html>
<script>
    var type;
    $(function () {
        $('#tt').datagrid({
            fit: true,
            fitColumns: true,
            method: 'GET',
            toolbar: '#tb',
            url: '/right/rightmessage',
            pagination: true,
            singleSelect: true,
            pageSize : 10,
            pageList : [5,10,15],
            columns:[[
                {field:'right_id',title:'权限编号',width:100},
                {field:'right_name',title:'权限名称',width:100,editor: 'text'},
                {field:'action',title:'操作',width:80,align:'center',
                    formatter:function(value,row,index){
                        if (row.editing){	//如果处于编辑状态
                            var s = '<a href="#" onclick="saverow(this)">保存</a> ';
                            var c = '<a href="#" onclick="cancelrow(this)">取消</a>';
                            return s+c;
                        } else { //如果处于非编辑状态
                            var e = '<a href="#" onclick="editrow(this)">编辑</a> ';
                            var d = '<a href="#" onclick="deleterow(this)">删除</a>';
                            return e+d;
                        }
                    }
                }
            ]],
            onBeforeEdit:function(index,row){
                row.editing = true;
                updateActions(index);
            },
            onAfterEdit:function(index,row){
                row.editing = false;
                updateActions(index);
            },
            onCancelEdit:function(index,row){
                row.editing = false;
                updateActions(index);
            }
        });
    });

    //更新行
    function updateActions(index){
        $('#tt').datagrid('updateRow',{
            index: index
        });
    }

    //获取行索引
    function getRowIndex(target){
        var tr = $(target).closest('tr.datagrid-row');
        return parseInt(tr.attr('datagrid-row-index'));
    }

    //点击增加时
    function insert(){
        type = 1;
        $('#tt').datagrid('insertRow', {
            index: 0,
            row:{}
        });
        $('#tt').datagrid('selectRow',0);
        $('#tt').datagrid('beginEdit',0);
    }

    //点击编辑时
    function editrow(target){
        type = 2;
        $('#tt').datagrid('beginEdit', getRowIndex(target));
    }

    //点击删除时
    function deleterow(target){
        $.messager.confirm('验证','确定删除?',function(r){
            if (r){
                $('#tt').datagrid('deleteRow', getRowIndex(target));
                var rows = $('#tt').datagrid('getChanges', 'deleted');
                var url = '/right/deleteright';
                var data = {right_id:rows[0].right_id};
                ajaxApi(url, data);
            }
        });
    }

    //点击保存时
    function saverow(target){
        $('#tt').datagrid('endEdit', getRowIndex(target));
        if(type == 1) { //表示增加
            var rows = $('#tt').datagrid('getChanges', 'inserted');
            var url = '/right/insertright'
        }

        if(type == 2) { //表示更新
            var rows = $('#tt').datagrid('getChanges', 'updated');
            var url = '/right/changeright'
        }

        console.log(rows);
        var data = {right_id:rows[0].right_id,right_name:rows[0].right_name};
        ajaxApi(url, data);
    }
    function cancelrow(target){
        if(type == 1)
        {
            $('#tt').datagrid('deleteRow', getRowIndex(target));
        }else{
            $('#tt').datagrid('cancelEdit', getRowIndex(target));
        }

    }

    function ajaxApi(url, data) {
        /*console.log(data);*/
        $.ajax({
            type : 'POST',
            url : url,
            data :
            {
                data : data
            },
            dataType : 'json',
            success: function (msg) {
                /*alert(msg);*/
                window.location.reload();
            }
        });
    }
</script>