<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.4.5/themes/gray/easyui.css">
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.4.5/themes/icon.css">
    <script type="text/javascript" src="/jquery-easyui-1.4.5/jquery.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.4.5/jquery.easyui.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.4.5/locale/easyui-lang-zh_CN.js"></script>

</head>
<body>

<table id="pp">
    <div id="tb">
        <a id="" class="easyui-linkbutton" handler="addrow" onclick="addrow()" data-options="iconCls:'icon-add',plain:true"/>添加</ a>
        </div>
</table>
</body>
</html>
<script>
    $('#pp').datagrid({
        fit: true,
        fitColumns: true,
        method: 'GET',
        toolbar: '#tb',
        url: '/administration/testmessage',
        pagination: true,
        singleSelect: true,
        pageSize : 5,
        pageList : [5,10,15],
        columns: [[
            {field: 'user_id', title: '人员编号', width: "20%"},
            {field: 'staff', title: '登录名', width: "40%"},
            {field: 'action', title: '操作', width: 70, align: 'center',
                formatter: function (value, row, index) {
                    if (row.editing) {
                        var s = '<a href="#" onclick="saverow(' + index + ')">保存</a> ';
                        var c = '<a href="#" onclick="cancelrow(' + index + ')">取消</a>';
                        return s + c;
                    } else {
                        var e = '<a href="#" onclick="editrow(' + index + ')">编辑</a> ';
                        var d = '<a href="#" onclick="deleterow(' + index + ')">删除</a>';
                        return e + d;
                    }
                }
            }
    ]],
    onBeforeEdit:function(index,row){
        row.editing = true;
        $('#pp').datagrid('refreshRow', index);
        editcount++;
    },
    onAfterEdit:function(index,row){
        row.editing = false;
        $('#pp').datagrid('refreshRow', index);
        editcount--;
    },
    onCancelEdit:function(index,row){
        row.editing = false;
        $('#pp').datagrid('refreshRow', index);
        editcount--;
    }
    }).datagrid('loadData',users).datagrid('acceptChanges');


    var editcount = 0;
    function editrow(index){
        $('#pp').datagrid('beginEdit', index);
    }
    function deleterow(index){
        $.messager.confirm('确认','是否真的删除?',function(r){
            if (r){
                $('#tt').datagrid('deleteRow', index);
            }
        });
    }
    function saverow(index){
        $('#pp').datagrid('endEdit', index);
    }
    function cancelrow(index){
        $('#pp').datagrid('cancelEdit', index);
    }
    function addrow(){
        if (editcount > 0){
            $.messager.alert('警告','当前还有'+editcount+'记录正在编辑，不能增加记录。');
            return;
        }
        $('#pp').datagrid('appendRow',{
            user_id:'',
            staff:''
        });
    }
    function saveall(){
        $('#pp').datagrid('acceptChanges');
    }
    function cancelall(){
        $('#pp').datagrid('rejectChanges');
    }
</script>

