<html>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.3.5/themes/gray/easyui.css">
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.3.5/themes/icon.css">
    <script type="text/javascript" src="/jquery-easyui-1.3.5/jquery.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.3.5/jquery.easyui.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.3.5/locale/easyui-lang-zh_CN.js"></script>

</head>

<body>
<div id="tb">
    <a href="#" class="easyui-linkbutton" onclick="insert()" data-options="iconCls:'icon-add',plain:true"/>添加</a>
</div>
<table id="tt"></table>
</body>
</html>
<script>
    var type;
    $(function () {
        $('#tt').datagrid({
            fit: true,
            fitColumns: true,
            method: 'GET',
            toolbar: '#tb',
            url: '/administration/usermessage',
            pagination: true,
            singleSelect: true,
            pageSize : 10,
            pageList : [5,10,15],
            columns:[[
                {field:'user_id',title:'编号',width:100},
                {field:'user_name',title:'登录名',width:100,editor: 'text'},
                {field:'staff',title:'人员姓名',width:100,editor: 'text'},
                {field:'phone',title:'电话',width:100,editor: 'text'},
                {field:'mail',title:'邮箱',width:100,editor: 'text'},
                {field:'power',title:'权限',width:100,
                    editor:{
                        type:'combobox',
                        options:{
                            valueField:'label',
                            textField:'value',
                            required:true,
                            editable:false,
                            data: [{
                                label: '1',
                                value: '普通用户'
                            },{
                                label: '5',
                                value: '管理员'
                            },{
                                label: '9',
                                value: '超级管理员'
                            }],
                            panelHeight:65
                        }
                    },
                    formatter: function(value,row,index){
                        if (value==1){
                            return "普通用户";
                        }
                        if(value==5) {
                            return "管理员";
                        }
                        if(value==9) {
                            return "超级管理员";
                        }
                    }
                },
                {field:'effective',title:'有效性',width:100,
                    editor:{
                        type:'combobox',
                        options:{
                            valueField:'label',
                            textField:'value',
                            required:true,
                            editable:false,
                            data: [{
                                label: '0',
                                value: '有效'
                            },{
                                label: '1',
                                value: '暂停'
                            }],
                            panelHeight:45
                        }
                    },
                    formatter: function(value,row,index){
                        if (value==0){
                            return "有效";
                        } else {
                            return "暂停";
                        }
                    }
                },
                {field:'action',title:'操作',width:80,align:'center',
                    formatter:function(value,row,index){
                        if (row.editing){	//如果处于编辑状态
                            var s = '<a href="#" onclick="saverow(this)">保存</a> ';
                            var c = '<a href="#" onclick="cancelrow(this)">取消</a>';
                            return s+c;
                        } else { //如果处于非编辑状态
                            var e = '<a href="#" onclick="editrow(this)">编辑</a> ';
                            /*var d = '<a href="#" onclick="deleterow(this)">删除</a>';*/
                            return e/*+d*/;
                        }
                    }
                }
            ]],
            onBeforeEdit:function(index,row){
                row.editing = true;
                updateActions(index);
            },
            onAfterEdit:function(index,row){
                row.editing = false;
                updateActions(index);
            },
            onCancelEdit:function(index,row){
                row.editing = false;
                updateActions(index);
            }
        });
    });

    //更新行
    function updateActions(index){
        $('#tt').datagrid('updateRow',{
            index: index
        });
    }

    //获取行索引
    function getRowIndex(target){
        var tr = $(target).closest('tr.datagrid-row');
        return parseInt(tr.attr('datagrid-row-index'));
    }

    //点击增加时
    function insert(){
        type = 1;
        $('#tt').datagrid('insertRow', {
            index: 0,
            row:{}
        });
        $('#tt').datagrid('selectRow',0);
        $('#tt').datagrid('beginEdit',0);
    }

    //点击编辑时
    function editrow(target){
        type = 2;
        $('#tt').datagrid('beginEdit', getRowIndex(target));
    }

//    //点击删除时
//    function deleterow(target){
//        $.messager.confirm('验证','确定删除?',function(r){
//            if (r){
//                $('#tt').datagrid('deleteRow', getRowIndex(target));
//                var rows = $('#tt').datagrid('getChanges', 'deleted');
//                var url = '';
//                var data = {id:rows[0].id};
//                ajaxApi(url, data);
//            }
//        });
//    }

    //点击保存时
    function saverow(target){
        $('#tt').datagrid('endEdit', getRowIndex(target));
        if(type == 1) { //表示增加
            var rows = $('#tt').datagrid('getChanges', 'inserted');
            var url = '/administration/insertuser'
        }

        if(type == 2) { //表示更新
            var rows = $('#tt').datagrid('getChanges', 'updated');
            var url = '/administration/changeuser'
        }

        console.log(rows);
        var data = {
            user_id:rows[0].user_id,
            user_name:rows[0].user_name,
            staff:rows[0].staff,
            phone:rows[0].phone,
            mail:rows[0].mail,
            effective:rows[0].effective,
            power:rows[0].power
        };
        ajaxApi(url, data);
    }
    function cancelrow(target){
        if(type == 1)
        {
            $('#tt').datagrid('deleteRow', getRowIndex(target));
        }else{
            $('#tt').datagrid('cancelEdit', getRowIndex(target));
        }

    }

    function ajaxApi(url, data) {
        console.log(data);
        $.ajax({
            KB : 'POST',
            url : url,
            data :
            {
                data : data
            },
            dataKB : 'json',
            success: function () {
                /*alert(msg);*/
                window.location.reload();
            }
        });
    }
</script>