<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.4.5/themes/gray/easyui.css">
    <link rel="stylesheet" type="text/css"
          href="/jquery-easyui-1.4.5/themes/icon.css">
    <script type="text/javascript" src="/jquery-easyui-1.4.5/jquery.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.4.5/jquery.easyui.min.js"></script>
    <script type="text/javascript" src="/jquery-easyui-1.4.5/locale/easyui-lang-zh_CN.js"></script>

    <script type="text/javascript">
        $(function() {
            $("#tree").tree({//把id为tree的对象加载成“tree”样式
                lines:true,
                data : [
                    {
                        text:"巡检",
                        "state": "closed",
                        "children": [
                                <?php
                        $date = $this->date;
                        if($date)
                        {
                            echo'
                            {
                                text:"填写巡检表",
                                iconCls:"",
                                attributes:
                                {
                                    url:"/inspection/inspection"
                                }
                            },';
                        }
                         ?>{
                                text:"查看巡检安排",
                                iconCls:"",
                                attributes:
                                {
                                    url:"/inspection/schedulemessage"
                                }
                            },
                            {
                                text:"查看巡检报表",
                                iconCls:"",
                                attributes:
                                {
                                    url:"/inspection/report"
                                }
                            }]
                    },
                    {
                        "text": "任务",
                        iconCls: "",
                        "state": "closed",
                        "children": [{
                            text:"查看未完成任务",
                            attributes:
                            {
                                url:"/task/unfinished"
                            }
                        },
                            {
                                text:"查看已完成任务",
                                attributes:
                                {
                                    url:"/task/finished"
                                }
                            }]
                    },{
                        text:"知识库",
                        "state": "closed",
                        "children": [{
                            text:"总览",
                            attributes:
                            {
                                url:"/kb/kb"
                            }
                        }]
                    },
                    {
                        text:"修改个人信息",
                        iconCls:"",
                        attributes:
                        {
                            url:"/message/message"
                        }
                    },
                    {
                        text:"安全退出",
                        iconCls:"icon-back"
                    }],
                onClick : function(node) {
                    if (node.attributes) {
                        openTab(node.text, node.attributes.url, node.iconCls);
                    }
                    if (node.text == "安全退出") {
                        exit();
                    }
                }
            });

            function exit() {
                $.messager.confirm('系统提示', '您确定要退出系统吗？', function(r)//r是获取确定或取消
                {
                    if (r) {
                        window.location.href = '/login/login?flag=1';
                    }
                });
            }

            function openTab(text, url, icon) {
                if ($("#tabs").tabs('exists', text)) {
                    $("#tabs").tabs('select', text);
                } else {
                    var content = "<iframe frameborder='0' scrolling='auto' style='width:100%;height:100%;' src="
                        + url + "></iframe>";//与div的不同，显示url里的页面
                    $("#tabs").tabs('add', {
                        title : text,
                        closable : true,//可关闭
                        iconCls : icon,
                        content : content
                    });
                }
            }
        });
    </script>

</head>

<body class="easyui-layout">

<div region="north"
     style="height:80px; background-image:url(/images/logo1.png);background-repeat:no-repeat;">
</div>
<div region="west" style="width: 220px;padding: 5px;" title="导航菜单" split="true">
    <ul id="tree" class="easyui-tree"></ul>
</div>
<div region="center">
    <div class="easyui-tabs" fit="true" border="false" id="tabs">
        <div title="欢迎使用">
<h1 align="center">
            <?php
            $staff = $this->staff;
            echo "欢迎".$staff."进入任务处理模块！"
            ?>
</h1>
        </div>
    </div>
</div>

</body>
</html>