<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <!-- 此时表示根据设备大小调整页面的显示宽度 -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap需要jQuery的支持，所以要导入jQuery的开发包 -->
    <script type="text/javascript" src="/js/jquery-1.11.3/jquery.min.js"></script>
    <script type="text/javascript" src="/bootstrap-3.3.6/dist/js/bootstrap.min.js"></script>
    <link type="text/css" href="/bootstrap-3.3.6/dist/css/bootstrap.min.css" rel="stylesheet">
    <link type="text/css" href="/bootstrap-3.3.6/dist/css/bootstrap-theme.min.css" rel="stylesheet">
<title>赛尔网络</title>
</head>

<body>
<div style="height: 85px">
    <!--导航栏-->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="height: 85px">
        <!--容器-->
        <div class="container-fluid">
            <!-- -->
            <div class="navbar-header">
                <!--右侧按钮，当屏幕变小时出现-->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <!--按钮上的横线-->
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--左侧图标-->
                <a class="navbar-brand" href="#">
                    <img alt="Brand" src="/images/logo.png">
                </a>
            </div>
            <!--导航按钮-->
            <!--当屏幕变小时，以下按钮会收到右侧按钮中-->
            <!--id不可更改-->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <br><br>
                <ul class="nav navbar-nav">
                    <li><a href="index"><b>首页</b><span class="sr-only">(current)</span></a></li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">监控中心<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="../monitor/host">主机</a></li>
                            <li><a href="">网络设备监控</a></li>
                            <li><a href="">中间件</a></li>
                            <li><a href="">安全设备</a></li>
                            <li><a href="">数据库</a></li>
                            <li><a href="">存储</a></li>
                            <li><a href="">web服务</a></li>
                            <li><a href="">应用服务</a></li>
                            <!--另起一类-->
                            <!--<li role="separator" class="divider"></li>-->
                        </ul>
                    </li>
                    <li><a href="#">事件中心<span class="sr-only">(current)</span></a></li>
                    <li><a href="#">日志中心<span class="sr-only">(current)</span></a></li>
                    <li><a href="#">拓扑图<span class="sr-only">(current)</span></a></li>
                    <li><a href="#">管理中心<span class="sr-only">(current)</span></a></li>
                    <li><a href="#">报表中心<span class="sr-only">(current)</span></a></li>
                </ul>
                <!--搜索框-->
                <!--<form class="navbar-form navbar-right" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>-->
            </div>
        </div>
    </nav>
</div>
<div>
    <div class="panel panel-default" style="width: 45%;float:left">
        <div class="panel-heading">
            <h3 class="panel-title">告警信息</h3>
        </div>
        <div class="panel-body">
            Panel content
        </div>
    </div>
    <div class="panel panel-default" style="width: 45%;float:right">
        <div class="panel-heading">
            <h3 class="panel-title">事件趋势</h3>
        </div>
        <div class="panel-body">
            Panel content
        </div>
    </div>
</div>

</body>
</html>
